# Generated by Django 2.2 on 2022-04-07 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('isMain', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('percentSuccess', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PingTestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('loadingTime', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkOfPage', to='checkStatus.Page')),
                ('pingTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingTestStatus', to='checkStatus.PingTest')),
            ],
        ),
        migrations.AddField(
            model_name='pingtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testPing', to='checkStatus.Test'),
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testType', to='checkStatus.Test')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='pageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testLink', to='checkStatus.PageType'),
        ),
        migrations.AddField(
            model_name='page',
            name='pingTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingTestLink', to='checkStatus.PingTest'),
        ),
    ]
