# Generated by Django 2.2 on 2022-04-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkStatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pingTest',
        ),
    ]
