# Generated by Django 2.2 on 2022-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkStatus', '0002_remove_page_pingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingtest',
            name='onlyMain',
            field=models.BooleanField(default=False),
        ),
    ]
